# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainapp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1422, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 900))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 1361, 800))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(1000, 800))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 811))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1892, 845))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.yr1_label = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.yr1_label.setFlat(True)
        self.yr1_label.setObjectName("yr1_label")
        self.verticalLayout.addWidget(self.yr1_label)
        self.img1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.img1.setMinimumSize(QtCore.QSize(300, 500))
        self.img1.setText("")
        self.img1.setAlignment(QtCore.Qt.AlignCenter)
        self.img1.setObjectName("img1")
        self.verticalLayout.addWidget(self.img1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName("formLayout")
        self.l1yr1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.l1yr1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l1yr1.sizePolicy().hasHeightForWidth())
        self.l1yr1.setSizePolicy(sizePolicy)
        self.l1yr1.setMinimumSize(QtCore.QSize(100, 0))
        self.l1yr1.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.l1yr1.setCheckable(True)
        self.l1yr1.setAutoExclusive(True)
        self.l1yr1.setObjectName("l1yr1")
        self.buttonGroup1 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup1.setObjectName("buttonGroup1")
        self.buttonGroup1.setExclusive(False)
        self.buttonGroup1.addButton(self.l1yr1)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.l1yr1)
        self.l2yr1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l2yr1.sizePolicy().hasHeightForWidth())
        self.l2yr1.setSizePolicy(sizePolicy)
        self.l2yr1.setMinimumSize(QtCore.QSize(100, 0))
        self.l2yr1.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.l2yr1.setCheckable(True)
        self.l2yr1.setAutoExclusive(True)
        self.l2yr1.setObjectName("l2yr1")
        self.buttonGroup1.addButton(self.l2yr1)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.l2yr1)
        self.t1yr1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t1yr1.sizePolicy().hasHeightForWidth())
        self.t1yr1.setSizePolicy(sizePolicy)
        self.t1yr1.setMinimumSize(QtCore.QSize(100, 0))
        self.t1yr1.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.t1yr1.setCheckable(True)
        self.t1yr1.setAutoExclusive(True)
        self.t1yr1.setObjectName("t1yr1")
        self.buttonGroup1.addButton(self.t1yr1)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.t1yr1)
        self.t2yr1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t2yr1.sizePolicy().hasHeightForWidth())
        self.t2yr1.setSizePolicy(sizePolicy)
        self.t2yr1.setMinimumSize(QtCore.QSize(100, 0))
        self.t2yr1.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.t2yr1.setCheckable(True)
        self.t2yr1.setAutoExclusive(True)
        self.t2yr1.setObjectName("t2yr1")
        self.buttonGroup1.addButton(self.t2yr1)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.t2yr1)
        self.ccyr1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ccyr1.sizePolicy().hasHeightForWidth())
        self.ccyr1.setSizePolicy(sizePolicy)
        self.ccyr1.setMinimumSize(QtCore.QSize(100, 0))
        self.ccyr1.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.ccyr1.setCheckable(True)
        self.ccyr1.setAutoExclusive(True)
        self.ccyr1.setObjectName("ccyr1")
        self.buttonGroup1.addButton(self.ccyr1)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.ccyr1)
        self.ssyr1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssyr1.sizePolicy().hasHeightForWidth())
        self.ssyr1.setSizePolicy(sizePolicy)
        self.ssyr1.setMinimumSize(QtCore.QSize(100, 0))
        self.ssyr1.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.ssyr1.setCheckable(True)
        self.ssyr1.setAutoExclusive(True)
        self.ssyr1.setObjectName("ssyr1")
        self.buttonGroup1.addButton(self.ssyr1)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ssyr1)
        self.ncyr1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.ncyr1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ncyr1.sizePolicy().hasHeightForWidth())
        self.ncyr1.setSizePolicy(sizePolicy)
        self.ncyr1.setMinimumSize(QtCore.QSize(100, 0))
        self.ncyr1.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.ncyr1.setCheckable(True)
        self.ncyr1.setAutoExclusive(True)
        self.ncyr1.setObjectName("ncyr1")
        self.buttonGroup1.addButton(self.ncyr1)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.ncyr1)
        self.eyr1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eyr1.sizePolicy().hasHeightForWidth())
        self.eyr1.setSizePolicy(sizePolicy)
        self.eyr1.setMinimumSize(QtCore.QSize(100, 0))
        self.eyr1.setStyleSheet("QPushButton{\n"
"background-color : white;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font :  14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.eyr1.setCheckable(True)
        self.eyr1.setAutoExclusive(True)
        self.eyr1.setObjectName("eyr1")
        self.buttonGroup1.addButton(self.eyr1)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.eyr1)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.commentsyr1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commentsyr1.sizePolicy().hasHeightForWidth())
        self.commentsyr1.setSizePolicy(sizePolicy)
        self.commentsyr1.setMaximumSize(QtCore.QSize(220, 16777215))
        self.commentsyr1.setTabletTracking(False)
        self.commentsyr1.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.commentsyr1.setInputMask("")
        self.commentsyr1.setCursorPosition(11)
        self.commentsyr1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.commentsyr1.setDragEnabled(False)
        self.commentsyr1.setObjectName("commentsyr1")
        self.horizontalLayout_3.addWidget(self.commentsyr1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.repyr1 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.repyr1.sizePolicy().hasHeightForWidth())
        self.repyr1.setSizePolicy(sizePolicy)
        self.repyr1.setMinimumSize(QtCore.QSize(100, 0))
        self.repyr1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.repyr1.setObjectName("repyr1")
        self.horizontalLayout_8.addWidget(self.repyr1)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.yr2_label = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.yr2_label.setFlat(True)
        self.yr2_label.setObjectName("yr2_label")
        self.verticalLayout_2.addWidget(self.yr2_label)
        self.img2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.img2.setMinimumSize(QtCore.QSize(300, 500))
        self.img2.setText("")
        self.img2.setAlignment(QtCore.Qt.AlignCenter)
        self.img2.setObjectName("img2")
        self.verticalLayout_2.addWidget(self.img2)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_2.setObjectName("formLayout_2")
        self.l1yr2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.l1yr2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l1yr2.sizePolicy().hasHeightForWidth())
        self.l1yr2.setSizePolicy(sizePolicy)
        self.l1yr2.setMinimumSize(QtCore.QSize(100, 0))
        self.l1yr2.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.l1yr2.setCheckable(True)
        self.l1yr2.setAutoExclusive(True)
        self.l1yr2.setObjectName("l1yr2")
        self.buttonGroup2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup2.setObjectName("buttonGroup2")
        self.buttonGroup2.setExclusive(False)
        self.buttonGroup2.addButton(self.l1yr2)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.l1yr2)
        self.l2yr2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l2yr2.sizePolicy().hasHeightForWidth())
        self.l2yr2.setSizePolicy(sizePolicy)
        self.l2yr2.setMinimumSize(QtCore.QSize(100, 0))
        self.l2yr2.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.l2yr2.setCheckable(True)
        self.l2yr2.setAutoExclusive(True)
        self.l2yr2.setObjectName("l2yr2")
        self.buttonGroup2.addButton(self.l2yr2)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.l2yr2)
        self.t1yr2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t1yr2.sizePolicy().hasHeightForWidth())
        self.t1yr2.setSizePolicy(sizePolicy)
        self.t1yr2.setMinimumSize(QtCore.QSize(100, 0))
        self.t1yr2.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.t1yr2.setCheckable(True)
        self.t1yr2.setAutoExclusive(True)
        self.t1yr2.setObjectName("t1yr2")
        self.buttonGroup2.addButton(self.t1yr2)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.t1yr2)
        self.t2yr2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t2yr2.sizePolicy().hasHeightForWidth())
        self.t2yr2.setSizePolicy(sizePolicy)
        self.t2yr2.setMinimumSize(QtCore.QSize(100, 0))
        self.t2yr2.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.t2yr2.setCheckable(True)
        self.t2yr2.setAutoExclusive(True)
        self.t2yr2.setObjectName("t2yr2")
        self.buttonGroup2.addButton(self.t2yr2)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.t2yr2)
        self.ccyr2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ccyr2.sizePolicy().hasHeightForWidth())
        self.ccyr2.setSizePolicy(sizePolicy)
        self.ccyr2.setMinimumSize(QtCore.QSize(100, 0))
        self.ccyr2.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.ccyr2.setCheckable(True)
        self.ccyr2.setAutoExclusive(True)
        self.ccyr2.setObjectName("ccyr2")
        self.buttonGroup2.addButton(self.ccyr2)
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.ccyr2)
        self.ssyr2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssyr2.sizePolicy().hasHeightForWidth())
        self.ssyr2.setSizePolicy(sizePolicy)
        self.ssyr2.setMinimumSize(QtCore.QSize(100, 0))
        self.ssyr2.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.ssyr2.setCheckable(True)
        self.ssyr2.setAutoExclusive(True)
        self.ssyr2.setObjectName("ssyr2")
        self.buttonGroup2.addButton(self.ssyr2)
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ssyr2)
        self.ncyr2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.ncyr2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ncyr2.sizePolicy().hasHeightForWidth())
        self.ncyr2.setSizePolicy(sizePolicy)
        self.ncyr2.setMinimumSize(QtCore.QSize(100, 0))
        self.ncyr2.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.ncyr2.setCheckable(True)
        self.ncyr2.setAutoExclusive(True)
        self.ncyr2.setObjectName("ncyr2")
        self.buttonGroup2.addButton(self.ncyr2)
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.ncyr2)
        self.eyr2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eyr2.sizePolicy().hasHeightForWidth())
        self.eyr2.setSizePolicy(sizePolicy)
        self.eyr2.setMinimumSize(QtCore.QSize(100, 0))
        self.eyr2.setStyleSheet("QPushButton{\n"
"background-color : white;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font :  14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.eyr2.setCheckable(True)
        self.eyr2.setAutoExclusive(True)
        self.eyr2.setObjectName("eyr2")
        self.buttonGroup2.addButton(self.eyr2)
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.eyr2)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.commentsyr2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commentsyr2.sizePolicy().hasHeightForWidth())
        self.commentsyr2.setSizePolicy(sizePolicy)
        self.commentsyr2.setMaximumSize(QtCore.QSize(220, 16777215))
        self.commentsyr2.setTabletTracking(False)
        self.commentsyr2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.commentsyr2.setInputMask("")
        self.commentsyr2.setCursorPosition(11)
        self.commentsyr2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.commentsyr2.setDragEnabled(False)
        self.commentsyr2.setObjectName("commentsyr2")
        self.horizontalLayout_4.addWidget(self.commentsyr2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.repyr2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.repyr2.sizePolicy().hasHeightForWidth())
        self.repyr2.setSizePolicy(sizePolicy)
        self.repyr2.setMinimumSize(QtCore.QSize(100, 0))
        self.repyr2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.repyr2.setObjectName("repyr2")
        self.horizontalLayout_9.addWidget(self.repyr2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.yr3_label = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.yr3_label.setFlat(True)
        self.yr3_label.setObjectName("yr3_label")
        self.verticalLayout_6.addWidget(self.yr3_label)
        self.img3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.img3.setMinimumSize(QtCore.QSize(300, 500))
        self.img3.setText("")
        self.img3.setAlignment(QtCore.Qt.AlignCenter)
        self.img3.setObjectName("img3")
        self.verticalLayout_6.addWidget(self.img3)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_5.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_5.setObjectName("formLayout_5")
        self.l1yr3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.l1yr3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l1yr3.sizePolicy().hasHeightForWidth())
        self.l1yr3.setSizePolicy(sizePolicy)
        self.l1yr3.setMinimumSize(QtCore.QSize(100, 0))
        self.l1yr3.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.l1yr3.setCheckable(True)
        self.l1yr3.setAutoExclusive(True)
        self.l1yr3.setObjectName("l1yr3")
        self.buttonGroup3 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup3.setObjectName("buttonGroup3")
        self.buttonGroup3.setExclusive(False)
        self.buttonGroup3.addButton(self.l1yr3)
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.l1yr3)
        self.l2yr3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l2yr3.sizePolicy().hasHeightForWidth())
        self.l2yr3.setSizePolicy(sizePolicy)
        self.l2yr3.setMinimumSize(QtCore.QSize(100, 0))
        self.l2yr3.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.l2yr3.setCheckable(True)
        self.l2yr3.setAutoExclusive(True)
        self.l2yr3.setObjectName("l2yr3")
        self.buttonGroup3.addButton(self.l2yr3)
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.l2yr3)
        self.t1yr3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t1yr3.sizePolicy().hasHeightForWidth())
        self.t1yr3.setSizePolicy(sizePolicy)
        self.t1yr3.setMinimumSize(QtCore.QSize(100, 0))
        self.t1yr3.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.t1yr3.setCheckable(True)
        self.t1yr3.setAutoExclusive(True)
        self.t1yr3.setObjectName("t1yr3")
        self.buttonGroup3.addButton(self.t1yr3)
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.t1yr3)
        self.t2yr3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t2yr3.sizePolicy().hasHeightForWidth())
        self.t2yr3.setSizePolicy(sizePolicy)
        self.t2yr3.setMinimumSize(QtCore.QSize(100, 0))
        self.t2yr3.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.t2yr3.setCheckable(True)
        self.t2yr3.setAutoExclusive(True)
        self.t2yr3.setObjectName("t2yr3")
        self.buttonGroup3.addButton(self.t2yr3)
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.t2yr3)
        self.ccyr3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ccyr3.sizePolicy().hasHeightForWidth())
        self.ccyr3.setSizePolicy(sizePolicy)
        self.ccyr3.setMinimumSize(QtCore.QSize(100, 0))
        self.ccyr3.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.ccyr3.setCheckable(True)
        self.ccyr3.setAutoExclusive(True)
        self.ccyr3.setObjectName("ccyr3")
        self.buttonGroup3.addButton(self.ccyr3)
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.ccyr3)
        self.ssyr3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssyr3.sizePolicy().hasHeightForWidth())
        self.ssyr3.setSizePolicy(sizePolicy)
        self.ssyr3.setMinimumSize(QtCore.QSize(100, 0))
        self.ssyr3.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.ssyr3.setCheckable(True)
        self.ssyr3.setAutoExclusive(True)
        self.ssyr3.setObjectName("ssyr3")
        self.buttonGroup3.addButton(self.ssyr3)
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ssyr3)
        self.ncyr3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.ncyr3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ncyr3.sizePolicy().hasHeightForWidth())
        self.ncyr3.setSizePolicy(sizePolicy)
        self.ncyr3.setMinimumSize(QtCore.QSize(100, 0))
        self.ncyr3.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.ncyr3.setCheckable(True)
        self.ncyr3.setAutoExclusive(True)
        self.ncyr3.setObjectName("ncyr3")
        self.buttonGroup3.addButton(self.ncyr3)
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.ncyr3)
        self.eyr3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eyr3.sizePolicy().hasHeightForWidth())
        self.eyr3.setSizePolicy(sizePolicy)
        self.eyr3.setMinimumSize(QtCore.QSize(100, 0))
        self.eyr3.setStyleSheet("QPushButton{\n"
"background-color : white;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font :  14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.eyr3.setCheckable(True)
        self.eyr3.setAutoExclusive(True)
        self.eyr3.setObjectName("eyr3")
        self.buttonGroup3.addButton(self.eyr3)
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.eyr3)
        self.verticalLayout_6.addLayout(self.formLayout_5)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.commentsyr3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commentsyr3.sizePolicy().hasHeightForWidth())
        self.commentsyr3.setSizePolicy(sizePolicy)
        self.commentsyr3.setMaximumSize(QtCore.QSize(220, 16777215))
        self.commentsyr3.setTabletTracking(False)
        self.commentsyr3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.commentsyr3.setInputMask("")
        self.commentsyr3.setCursorPosition(11)
        self.commentsyr3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.commentsyr3.setDragEnabled(False)
        self.commentsyr3.setObjectName("commentsyr3")
        self.horizontalLayout_12.addWidget(self.commentsyr3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.repyr3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.repyr3.sizePolicy().hasHeightForWidth())
        self.repyr3.setSizePolicy(sizePolicy)
        self.repyr3.setMinimumSize(QtCore.QSize(100, 0))
        self.repyr3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.repyr3.setObjectName("repyr3")
        self.horizontalLayout_13.addWidget(self.repyr3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.yr4_label = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.yr4_label.setFlat(True)
        self.yr4_label.setObjectName("yr4_label")
        self.verticalLayout_7.addWidget(self.yr4_label)
        self.img4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.img4.setMinimumSize(QtCore.QSize(300, 500))
        self.img4.setText("")
        self.img4.setAlignment(QtCore.Qt.AlignCenter)
        self.img4.setObjectName("img4")
        self.verticalLayout_7.addWidget(self.img4)
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_6.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_6.setObjectName("formLayout_6")
        self.l1yr4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.l1yr4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l1yr4.sizePolicy().hasHeightForWidth())
        self.l1yr4.setSizePolicy(sizePolicy)
        self.l1yr4.setMinimumSize(QtCore.QSize(100, 0))
        self.l1yr4.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.l1yr4.setCheckable(True)
        self.l1yr4.setAutoExclusive(True)
        self.l1yr4.setObjectName("l1yr4")
        self.buttonGroup4 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup4.setObjectName("buttonGroup4")
        self.buttonGroup4.setExclusive(False)
        self.buttonGroup4.addButton(self.l1yr4)
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.l1yr4)
        self.l2yr4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l2yr4.sizePolicy().hasHeightForWidth())
        self.l2yr4.setSizePolicy(sizePolicy)
        self.l2yr4.setMinimumSize(QtCore.QSize(100, 0))
        self.l2yr4.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.l2yr4.setCheckable(True)
        self.l2yr4.setAutoExclusive(True)
        self.l2yr4.setObjectName("l2yr4")
        self.buttonGroup4.addButton(self.l2yr4)
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.l2yr4)
        self.t1yr4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t1yr4.sizePolicy().hasHeightForWidth())
        self.t1yr4.setSizePolicy(sizePolicy)
        self.t1yr4.setMinimumSize(QtCore.QSize(100, 0))
        self.t1yr4.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.t1yr4.setCheckable(True)
        self.t1yr4.setAutoExclusive(True)
        self.t1yr4.setObjectName("t1yr4")
        self.buttonGroup4.addButton(self.t1yr4)
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.t1yr4)
        self.t2yr4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t2yr4.sizePolicy().hasHeightForWidth())
        self.t2yr4.setSizePolicy(sizePolicy)
        self.t2yr4.setMinimumSize(QtCore.QSize(100, 0))
        self.t2yr4.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.t2yr4.setCheckable(True)
        self.t2yr4.setAutoExclusive(True)
        self.t2yr4.setObjectName("t2yr4")
        self.buttonGroup4.addButton(self.t2yr4)
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.t2yr4)
        self.ccyr4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ccyr4.sizePolicy().hasHeightForWidth())
        self.ccyr4.setSizePolicy(sizePolicy)
        self.ccyr4.setMinimumSize(QtCore.QSize(100, 0))
        self.ccyr4.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.ccyr4.setCheckable(True)
        self.ccyr4.setAutoExclusive(True)
        self.ccyr4.setObjectName("ccyr4")
        self.buttonGroup4.addButton(self.ccyr4)
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.ccyr4)
        self.ssyr4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssyr4.sizePolicy().hasHeightForWidth())
        self.ssyr4.setSizePolicy(sizePolicy)
        self.ssyr4.setMinimumSize(QtCore.QSize(100, 0))
        self.ssyr4.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.ssyr4.setCheckable(True)
        self.ssyr4.setAutoExclusive(True)
        self.ssyr4.setObjectName("ssyr4")
        self.buttonGroup4.addButton(self.ssyr4)
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ssyr4)
        self.ncyr4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.ncyr4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ncyr4.sizePolicy().hasHeightForWidth())
        self.ncyr4.setSizePolicy(sizePolicy)
        self.ncyr4.setMinimumSize(QtCore.QSize(100, 0))
        self.ncyr4.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.ncyr4.setCheckable(True)
        self.ncyr4.setAutoExclusive(True)
        self.ncyr4.setObjectName("ncyr4")
        self.buttonGroup4.addButton(self.ncyr4)
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.ncyr4)
        self.eyr4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eyr4.sizePolicy().hasHeightForWidth())
        self.eyr4.setSizePolicy(sizePolicy)
        self.eyr4.setMinimumSize(QtCore.QSize(100, 0))
        self.eyr4.setStyleSheet("QPushButton{\n"
"background-color : white;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font :  14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.eyr4.setCheckable(True)
        self.eyr4.setAutoExclusive(True)
        self.eyr4.setObjectName("eyr4")
        self.buttonGroup4.addButton(self.eyr4)
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.eyr4)
        self.verticalLayout_7.addLayout(self.formLayout_6)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.commentsyr4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commentsyr4.sizePolicy().hasHeightForWidth())
        self.commentsyr4.setSizePolicy(sizePolicy)
        self.commentsyr4.setMaximumSize(QtCore.QSize(220, 16777215))
        self.commentsyr4.setTabletTracking(False)
        self.commentsyr4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.commentsyr4.setInputMask("")
        self.commentsyr4.setCursorPosition(11)
        self.commentsyr4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.commentsyr4.setDragEnabled(False)
        self.commentsyr4.setObjectName("commentsyr4")
        self.horizontalLayout_14.addWidget(self.commentsyr4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.repyr4 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.repyr4.sizePolicy().hasHeightForWidth())
        self.repyr4.setSizePolicy(sizePolicy)
        self.repyr4.setMinimumSize(QtCore.QSize(100, 0))
        self.repyr4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.repyr4.setObjectName("repyr4")
        self.horizontalLayout_15.addWidget(self.repyr4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.yr5_label = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.yr5_label.setFlat(True)
        self.yr5_label.setObjectName("yr5_label")
        self.verticalLayout_8.addWidget(self.yr5_label)
        self.img5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.img5.setMinimumSize(QtCore.QSize(300, 500))
        self.img5.setText("")
        self.img5.setAlignment(QtCore.Qt.AlignCenter)
        self.img5.setObjectName("img5")
        self.verticalLayout_8.addWidget(self.img5)
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_7.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_7.setObjectName("formLayout_7")
        self.l1yr5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.l1yr5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l1yr5.sizePolicy().hasHeightForWidth())
        self.l1yr5.setSizePolicy(sizePolicy)
        self.l1yr5.setMinimumSize(QtCore.QSize(100, 0))
        self.l1yr5.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.l1yr5.setCheckable(True)
        self.l1yr5.setAutoExclusive(True)
        self.l1yr5.setObjectName("l1yr5")
        self.buttonGroup5 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup5.setObjectName("buttonGroup5")
        self.buttonGroup5.setExclusive(False)
        self.buttonGroup5.addButton(self.l1yr5)
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.l1yr5)
        self.l2yr5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l2yr5.sizePolicy().hasHeightForWidth())
        self.l2yr5.setSizePolicy(sizePolicy)
        self.l2yr5.setMinimumSize(QtCore.QSize(100, 0))
        self.l2yr5.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.l2yr5.setCheckable(True)
        self.l2yr5.setAutoExclusive(True)
        self.l2yr5.setObjectName("l2yr5")
        self.buttonGroup5.addButton(self.l2yr5)
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.l2yr5)
        self.t1yr5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t1yr5.sizePolicy().hasHeightForWidth())
        self.t1yr5.setSizePolicy(sizePolicy)
        self.t1yr5.setMinimumSize(QtCore.QSize(100, 0))
        self.t1yr5.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.t1yr5.setCheckable(True)
        self.t1yr5.setAutoExclusive(True)
        self.t1yr5.setObjectName("t1yr5")
        self.buttonGroup5.addButton(self.t1yr5)
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.t1yr5)
        self.t2yr5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t2yr5.sizePolicy().hasHeightForWidth())
        self.t2yr5.setSizePolicy(sizePolicy)
        self.t2yr5.setMinimumSize(QtCore.QSize(100, 0))
        self.t2yr5.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.t2yr5.setCheckable(True)
        self.t2yr5.setAutoExclusive(True)
        self.t2yr5.setObjectName("t2yr5")
        self.buttonGroup5.addButton(self.t2yr5)
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.t2yr5)
        self.ccyr5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ccyr5.sizePolicy().hasHeightForWidth())
        self.ccyr5.setSizePolicy(sizePolicy)
        self.ccyr5.setMinimumSize(QtCore.QSize(100, 0))
        self.ccyr5.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.ccyr5.setCheckable(True)
        self.ccyr5.setAutoExclusive(True)
        self.ccyr5.setObjectName("ccyr5")
        self.buttonGroup5.addButton(self.ccyr5)
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.ccyr5)
        self.ssyr5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssyr5.sizePolicy().hasHeightForWidth())
        self.ssyr5.setSizePolicy(sizePolicy)
        self.ssyr5.setMinimumSize(QtCore.QSize(100, 0))
        self.ssyr5.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.ssyr5.setCheckable(True)
        self.ssyr5.setAutoExclusive(True)
        self.ssyr5.setObjectName("ssyr5")
        self.buttonGroup5.addButton(self.ssyr5)
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ssyr5)
        self.ncyr5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.ncyr5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ncyr5.sizePolicy().hasHeightForWidth())
        self.ncyr5.setSizePolicy(sizePolicy)
        self.ncyr5.setMinimumSize(QtCore.QSize(100, 0))
        self.ncyr5.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.ncyr5.setCheckable(True)
        self.ncyr5.setAutoExclusive(True)
        self.ncyr5.setObjectName("ncyr5")
        self.buttonGroup5.addButton(self.ncyr5)
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.ncyr5)
        self.eyr5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eyr5.sizePolicy().hasHeightForWidth())
        self.eyr5.setSizePolicy(sizePolicy)
        self.eyr5.setMinimumSize(QtCore.QSize(100, 0))
        self.eyr5.setStyleSheet("QPushButton{\n"
"background-color : white;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font :  14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.eyr5.setCheckable(True)
        self.eyr5.setAutoExclusive(True)
        self.eyr5.setObjectName("eyr5")
        self.buttonGroup5.addButton(self.eyr5)
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.eyr5)
        self.verticalLayout_8.addLayout(self.formLayout_7)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.commentsyr5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commentsyr5.sizePolicy().hasHeightForWidth())
        self.commentsyr5.setSizePolicy(sizePolicy)
        self.commentsyr5.setMaximumSize(QtCore.QSize(220, 16777215))
        self.commentsyr5.setTabletTracking(False)
        self.commentsyr5.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.commentsyr5.setInputMask("")
        self.commentsyr5.setCursorPosition(11)
        self.commentsyr5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.commentsyr5.setDragEnabled(False)
        self.commentsyr5.setObjectName("commentsyr5")
        self.horizontalLayout_16.addWidget(self.commentsyr5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.repyr5 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.repyr5.sizePolicy().hasHeightForWidth())
        self.repyr5.setSizePolicy(sizePolicy)
        self.repyr5.setMinimumSize(QtCore.QSize(100, 0))
        self.repyr5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.repyr5.setObjectName("repyr5")
        self.horizontalLayout_17.addWidget(self.repyr5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.yr6_label = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.yr6_label.setFlat(True)
        self.yr6_label.setObjectName("yr6_label")
        self.verticalLayout_3.addWidget(self.yr6_label)
        self.img6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.img6.setMinimumSize(QtCore.QSize(300, 500))
        self.img6.setText("")
        self.img6.setAlignment(QtCore.Qt.AlignCenter)
        self.img6.setObjectName("img6")
        self.verticalLayout_3.addWidget(self.img6)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_3.setObjectName("formLayout_3")
        self.l1yr6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.l1yr6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l1yr6.sizePolicy().hasHeightForWidth())
        self.l1yr6.setSizePolicy(sizePolicy)
        self.l1yr6.setMinimumSize(QtCore.QSize(100, 0))
        self.l1yr6.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.l1yr6.setCheckable(True)
        self.l1yr6.setAutoExclusive(True)
        self.l1yr6.setObjectName("l1yr6")
        self.buttonGroup6 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup6.setObjectName("buttonGroup6")
        self.buttonGroup6.setExclusive(False)
        self.buttonGroup6.addButton(self.l1yr6)
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.l1yr6)
        self.l2yr6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l2yr6.sizePolicy().hasHeightForWidth())
        self.l2yr6.setSizePolicy(sizePolicy)
        self.l2yr6.setMinimumSize(QtCore.QSize(100, 0))
        self.l2yr6.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.l2yr6.setCheckable(True)
        self.l2yr6.setAutoExclusive(True)
        self.l2yr6.setObjectName("l2yr6")
        self.buttonGroup6.addButton(self.l2yr6)
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.l2yr6)
        self.t1yr6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t1yr6.sizePolicy().hasHeightForWidth())
        self.t1yr6.setSizePolicy(sizePolicy)
        self.t1yr6.setMinimumSize(QtCore.QSize(100, 0))
        self.t1yr6.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.t1yr6.setCheckable(True)
        self.t1yr6.setAutoExclusive(True)
        self.t1yr6.setObjectName("t1yr6")
        self.buttonGroup6.addButton(self.t1yr6)
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.t1yr6)
        self.t2yr6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t2yr6.sizePolicy().hasHeightForWidth())
        self.t2yr6.setSizePolicy(sizePolicy)
        self.t2yr6.setMinimumSize(QtCore.QSize(100, 0))
        self.t2yr6.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.t2yr6.setCheckable(True)
        self.t2yr6.setAutoExclusive(True)
        self.t2yr6.setObjectName("t2yr6")
        self.buttonGroup6.addButton(self.t2yr6)
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.t2yr6)
        self.ccyr6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ccyr6.sizePolicy().hasHeightForWidth())
        self.ccyr6.setSizePolicy(sizePolicy)
        self.ccyr6.setMinimumSize(QtCore.QSize(100, 0))
        self.ccyr6.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.ccyr6.setCheckable(True)
        self.ccyr6.setAutoExclusive(True)
        self.ccyr6.setObjectName("ccyr6")
        self.buttonGroup6.addButton(self.ccyr6)
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.ccyr6)
        self.ssyr6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssyr6.sizePolicy().hasHeightForWidth())
        self.ssyr6.setSizePolicy(sizePolicy)
        self.ssyr6.setMinimumSize(QtCore.QSize(100, 0))
        self.ssyr6.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.ssyr6.setCheckable(True)
        self.ssyr6.setAutoExclusive(True)
        self.ssyr6.setObjectName("ssyr6")
        self.buttonGroup6.addButton(self.ssyr6)
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ssyr6)
        self.ncyr6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.ncyr6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ncyr6.sizePolicy().hasHeightForWidth())
        self.ncyr6.setSizePolicy(sizePolicy)
        self.ncyr6.setMinimumSize(QtCore.QSize(100, 0))
        self.ncyr6.setStyleSheet("QPushButton{\n"
"background-color : gray;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font : bold 14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.ncyr6.setCheckable(True)
        self.ncyr6.setAutoExclusive(True)
        self.ncyr6.setObjectName("ncyr6")
        self.buttonGroup6.addButton(self.ncyr6)
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.ncyr6)
        self.eyr6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eyr6.sizePolicy().hasHeightForWidth())
        self.eyr6.setSizePolicy(sizePolicy)
        self.eyr6.setMinimumSize(QtCore.QSize(100, 0))
        self.eyr6.setStyleSheet("QPushButton{\n"
"background-color : white;\n"
"border-style : outset;\n"
"border-radius: 5px;\n"
"font :  14px;\n"
"adding : 2px;\n"
"}\n"
"QPushButton::checked{\n"
"background-color: green;\n"
"border-style : inset;\n"
"}")
        self.eyr6.setCheckable(True)
        self.eyr6.setAutoExclusive(True)
        self.eyr6.setObjectName("eyr6")
        self.buttonGroup6.addButton(self.eyr6)
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.eyr6)
        self.verticalLayout_3.addLayout(self.formLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.commentsyr6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commentsyr6.sizePolicy().hasHeightForWidth())
        self.commentsyr6.setSizePolicy(sizePolicy)
        self.commentsyr6.setMaximumSize(QtCore.QSize(220, 16777215))
        self.commentsyr6.setTabletTracking(False)
        self.commentsyr6.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.commentsyr6.setInputMask("")
        self.commentsyr6.setCursorPosition(11)
        self.commentsyr6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.commentsyr6.setDragEnabled(False)
        self.commentsyr6.setObjectName("commentsyr6")
        self.horizontalLayout_5.addWidget(self.commentsyr6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.repyr6 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.repyr6.sizePolicy().hasHeightForWidth())
        self.repyr6.setSizePolicy(sizePolicy)
        self.repyr6.setMinimumSize(QtCore.QSize(100, 0))
        self.repyr6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.repyr6.setObjectName("repyr6")
        self.horizontalLayout_10.addWidget(self.repyr6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.backButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.backButton.setStyleSheet("QPushButton{\n"
"background-color : red;\n"
"border-radius: 25px;\n"
"font :  14px;\n"
"padding : 2px;\n"
"max-width:50px;\n"
" max-height:50px;\n"
" min-width:50px;\n"
" min-height:50px;\n"
"}\n"
"QPushButton::pressed{\n"
"background-color: pink;\n"
"border-style : inset;\n"
"}")
        self.backButton.setObjectName("backButton")
        self.horizontalLayout_2.addWidget(self.backButton)
        self.slabLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slabLabel.sizePolicy().hasHeightForWidth())
        self.slabLabel.setSizePolicy(sizePolicy)
        self.slabLabel.setMinimumSize(QtCore.QSize(0, 25))
        self.slabLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        self.slabLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.slabLabel.setObjectName("slabLabel")
        self.horizontalLayout_2.addWidget(self.slabLabel)
        self.slabNo = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slabNo.sizePolicy().hasHeightForWidth())
        self.slabNo.setSizePolicy(sizePolicy)
        self.slabNo.setMaximumSize(QtCore.QSize(40, 16777215))
        self.slabNo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.slabNo.setReadOnly(False)
        self.slabNo.setObjectName("slabNo")
        self.horizontalLayout_2.addWidget(self.slabNo)
        self.numLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numLabel.sizePolicy().hasHeightForWidth())
        self.numLabel.setSizePolicy(sizePolicy)
        self.numLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.numLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        self.numLabel.setObjectName("numLabel")
        self.horizontalLayout_2.addWidget(self.numLabel)
        self.nextButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.nextButton.setStyleSheet("QPushButton{\n"
"background-color : green;\n"
"border-radius: 25px;\n"
"font :  14px;\n"
"padding : 2px;\n"
"max-width:50px;\n"
" max-height:50px;\n"
" min-width:50px;\n"
" min-height:50px;\n"
"}\n"
"QPushButton::pressed{\n"
"background-color: lightgreen;\n"
"border-style : inset;\n"
"}")
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout_2.addWidget(self.nextButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.saveButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.saveButton.setMinimumSize(QtCore.QSize(0, 0))
        self.saveButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.saveButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.saveButton.setFlat(False)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout_9.addWidget(self.saveButton, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addLayout(self.verticalLayout_9)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1422, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.yr1_label.setText(_translate("MainWindow", "PushButton"))
        self.l1yr1.setText(_translate("MainWindow", "L1"))
        self.l2yr1.setText(_translate("MainWindow", "L2"))
        self.t1yr1.setText(_translate("MainWindow", "T1"))
        self.t2yr1.setText(_translate("MainWindow", "T2"))
        self.ccyr1.setText(_translate("MainWindow", "CC"))
        self.ssyr1.setText(_translate("MainWindow", "SS"))
        self.ncyr1.setText(_translate("MainWindow", "NC"))
        self.eyr1.setText(_translate("MainWindow", "Error"))
        self.commentsyr1.setText(_translate("MainWindow", "Comments..."))
        self.repyr1.setText(_translate("MainWindow", "Replaced?"))
        self.yr2_label.setText(_translate("MainWindow", "PushButton"))
        self.l1yr2.setText(_translate("MainWindow", "L1"))
        self.l2yr2.setText(_translate("MainWindow", "L2"))
        self.t1yr2.setText(_translate("MainWindow", "T1"))
        self.t2yr2.setText(_translate("MainWindow", "T2"))
        self.ccyr2.setText(_translate("MainWindow", "CC"))
        self.ssyr2.setText(_translate("MainWindow", "SS"))
        self.ncyr2.setText(_translate("MainWindow", "NC"))
        self.eyr2.setText(_translate("MainWindow", "Error"))
        self.commentsyr2.setText(_translate("MainWindow", "Comments..."))
        self.repyr2.setText(_translate("MainWindow", "Replaced?"))
        self.yr3_label.setText(_translate("MainWindow", "PushButton"))
        self.l1yr3.setText(_translate("MainWindow", "L1"))
        self.l2yr3.setText(_translate("MainWindow", "L2"))
        self.t1yr3.setText(_translate("MainWindow", "T1"))
        self.t2yr3.setText(_translate("MainWindow", "T2"))
        self.ccyr3.setText(_translate("MainWindow", "CC"))
        self.ssyr3.setText(_translate("MainWindow", "SS"))
        self.ncyr3.setText(_translate("MainWindow", "NC"))
        self.eyr3.setText(_translate("MainWindow", "Error"))
        self.commentsyr3.setText(_translate("MainWindow", "Comments..."))
        self.repyr3.setText(_translate("MainWindow", "Replaced?"))
        self.yr4_label.setText(_translate("MainWindow", "PushButton"))
        self.l1yr4.setText(_translate("MainWindow", "L1"))
        self.l2yr4.setText(_translate("MainWindow", "L2"))
        self.t1yr4.setText(_translate("MainWindow", "T1"))
        self.t2yr4.setText(_translate("MainWindow", "T2"))
        self.ccyr4.setText(_translate("MainWindow", "CC"))
        self.ssyr4.setText(_translate("MainWindow", "SS"))
        self.ncyr4.setText(_translate("MainWindow", "NC"))
        self.eyr4.setText(_translate("MainWindow", "Error"))
        self.commentsyr4.setText(_translate("MainWindow", "Comments..."))
        self.repyr4.setText(_translate("MainWindow", "Replaced?"))
        self.yr5_label.setText(_translate("MainWindow", "PushButton"))
        self.l1yr5.setText(_translate("MainWindow", "L1"))
        self.l2yr5.setText(_translate("MainWindow", "L2"))
        self.t1yr5.setText(_translate("MainWindow", "T1"))
        self.t2yr5.setText(_translate("MainWindow", "T2"))
        self.ccyr5.setText(_translate("MainWindow", "CC"))
        self.ssyr5.setText(_translate("MainWindow", "SS"))
        self.ncyr5.setText(_translate("MainWindow", "NC"))
        self.eyr5.setText(_translate("MainWindow", "Error"))
        self.commentsyr5.setText(_translate("MainWindow", "Comments..."))
        self.repyr5.setText(_translate("MainWindow", "Replaced?"))
        self.yr6_label.setText(_translate("MainWindow", "PushButton"))
        self.l1yr6.setText(_translate("MainWindow", "L1"))
        self.l2yr6.setText(_translate("MainWindow", "L2"))
        self.t1yr6.setText(_translate("MainWindow", "T1"))
        self.t2yr6.setText(_translate("MainWindow", "T2"))
        self.ccyr6.setText(_translate("MainWindow", "CC"))
        self.ssyr6.setText(_translate("MainWindow", "SS"))
        self.ncyr6.setText(_translate("MainWindow", "NC"))
        self.eyr6.setText(_translate("MainWindow", "Error"))
        self.commentsyr6.setText(_translate("MainWindow", "Comments..."))
        self.repyr6.setText(_translate("MainWindow", "Replaced?"))
        self.backButton.setText(_translate("MainWindow", "<--"))
        self.slabLabel.setText(_translate("MainWindow", "Slab "))
        self.numLabel.setText(_translate("MainWindow", "/?"))
        self.nextButton.setText(_translate("MainWindow", "-->"))
        self.saveButton.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
